# Generated by Django 5.0 on 2023-12-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='text',
            new_name='content',
        ),
    ]
